
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e-com_development
test:
  <<: *default
  database: e-com_test
# You can use this database configuration with:
#  username: deploy
 #  password: 123abc!@#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
# ac01bbe48a7f295103b620d57b9eebdd69a18230ac1cded70bd5561ae19c5d304a39dc7c4bde54a12021399629f0fcfeef13560cab13705254f2531a4ab3d682
# Adding config/master.key to store the master encryption key: 68efb2953807324894a995d9b01714ae
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: ecom_production
  host: ''
